name: GitHub Action CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
    check-bats-version:
      runs-on: ubuntu-latest
      steps:
        - name: deploy
          uses: SamKirkland/web-deploy@v1
          with: 
            target-server: waitsuentkd.com/
            remote-user: ${{secrets.SSH}}
            private-ssh-key: ${{secrets.key}}
            source-path: TAS
            destination-path: /home2/waits3ql/public_html/tas
