name: GitHub Action CD

on:
  workflow_run:
    workflows: [ GitHub Action CI ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tas" 
          heroku_email: "tsye7393@colorado.edu"

