name: GitHub Action CI2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    check-bats-version:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: PHPUnit
          uses: chindit/actions-phpunit@1.0.0