name: GitHub Action CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    check-bats-version:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            extensions: curl, mysqli
            coverage: xdebug

        - name: composer
          uses: php-actions/composer@v6 # or alternative dependency management
        
        - name: PHPUnit tests
          uses: php-actions/phpunit@v3
          #run: composer install --prefer-dist --no-progress
          with:
            bootstrap: vendor/autoload.php
            configuration: test/phpunit.xml
            php_extensions: xdebug
            args: --coverage-text
            php_version: "8.1"
          env:
            XDEBUG_MODE: coverage