name: GitHub Action CI2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    check-bats-version:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            extensions: curl, mysqli
            coverage: xdebug
            
        - name: Install dependencies
          run: composer install --prefer-dist --no-progress

        - name: PHPUnit
          uses: chindit/actions-phpunit@1.0.0